export const MAIN_PAGE_NAME = 'MAIN_PAGE_NAME';
export const ABOUT_PAGE_NAME = 'ABOUT_PAGE_NAME';
export const DIAGNOSIS_PAGE_NAME = 'DIAGNOSIS_PAGE_NAME';
export const TREATMENT_PAGE_NAME = 'TREATMENT_PAGE_NAME';
export const OBSERVATION_PAGE_NAME = 'OBSERVATION_PAGE_NAME';

export const AOAMT_PAGE_NAME = 'AOAMT_PAGE_NAME';
export const REVIEWS_PAGE_NAME = 'REVIEWS_PAGE_NAME';
export const CREATE_ACCOUNT_NAME = 'CREATE_ACCOUNT_NAME';
export const PASSWORD_RECOVERY_NAME = 'PASSWORD_RECOVERY_NAME';
export const SIGN_IN_PAGE_NAME = 'SIGN_IN_PAGE_NAME';

export const PERSONAL_ACCOUNT_PAGE_NAME = 'PERSONAL_ACCOUNT_PAGE_NAME';
export const DESKTOP_PAGE_NAME = 'DESKTOP_PAGE_NAME';
export const CLINICS_PAGE_NAME = 'CLINICS_PAGE_NAME';

export const DOCTORS_PAGE_NAME = 'DOCTORS_PAGE_NAME';

export const APPLICATIONS_PAGE_NAME = 'APPLICATIONS_PAGE_NAME';
export const IT_SUPPORT_PAGE_NAME = 'IT_SUPPORT_PAGE_NAME';
export const DOCUMENTS_PAGE_NAME = 'DOCUMENTS_PAGE_NAME';
export const STATISTICS_PAGE_NAME = 'STATISTICS_PAGE_NAME';


export const SERVICES_PAGE_NAME = 'SERVICES_PAGE_NAME';
export const RECEPTION_PAGE_NAME = 'RECEPTION_PAGE_NAME';
export const PRIVACY_POLICY_PAGE_NAME = 'PRIVACY_POLICY_PAGE_NAME';
export const PERSONAL_DATA_PAGE_NAME = 'PERSONAL_DATA_PAGE_NAME';
